
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    env_file:
      - .env

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
